### ISSUE TITLE
test_tropical.py fails with the current version of the tropical code

### ISSUE THREAD

**Issue by lh64** [LoLab-VU/pysb#2]
Console output:
---------------------
Solving Simulation
Getting slaved species
Constructing Graph
Computing Cycles
Computing Conservation laws
Pruning Equations
Solving pruned equations
Traceback (most recent call last):
  File "/Users/lopezlab/git/pysb/pysb/tests/test_tropical.py", line 11, in <module>
    tropical.tropicalize(t, ignore=1, epsilon=0.1, rho=1, verbose=True)
  File "/Users/lopezlab/git/pysb/pysb/tools/tropicalize.py", line 57, in tropicalize
    self.sol_pruned = self.solve_pruned()
  File "/Users/lopezlab/git/pysb/pysb/tools/tropicalize.py", line 215, in solve_pruned
    self.sol_pruned = { j:sol[0][i] for i, j in enumerate(solve_for) }
  File "/Users/lopezlab/git/pysb/pysb/tools/tropicalize.py", line 215, in <dictcomp>
    self.sol_pruned = { j:sol[0][i] for i, j in enumerate(solve_for) }
KeyError: 0

**Comment by alubbock** [comment]
Fixed by @lh64 in 97223e1d7b79b6508418b07cd11f350759ea7483
