### ISSUE TITLE
pysb.bng._parse_reaction failing if multiple rules generate the same reaction

### ISSUE THREAD

**Issue by lh64** [LoLab-VU/pysb#6]
The BNG code was recently changed to output all rules that generate a given reaction to the NET file (BNG 2.2.5 and earlier only output the last rule detected that generated a reaction). The rules are output in the comment following the line in the 'reactions' block separated by commas, e.g., 

#rec_intern_10_2,rec_intern_11_2,rec_intern_11_2

This breaks the '_parse_reaction' method in pysb.bng, which looks for a match to the following regex:

r'#(_reverse_)?(\w+)(?: unit_conversion=(.*))?\s*$', rule).groups()

A match is not found since commas do not constitute "word" characters (i.e., \w+ doesn't match). An example traceback is:

Traceback (most recent call last):
  File "/Users/lopezlab/git/egfr/chen_sorger_2009_egfr/run.py", line 7, in <module>
    yout = odesolve(model, t, integrator='lsoda', verbose=True)
  File "/Users/lopezlab/git/pysb/pysb/integrate.py", line 395, in odesolve
    solver = Solver(model, tspan, integrator, cleanup, verbose, **integrator_options)
  File "/Users/lopezlab/git/pysb/pysb/integrate.py", line 99, in __init__
    pysb.bng.generate_equations(model,cleanup,self.verbose)
  File "/Users/lopezlab/git/pysb/pysb/bng.py", line 346, in generate_equations
    _parse_netfile(model, lines)
  File "/Users/lopezlab/git/pysb/pysb/bng.py", line 375, in _parse_netfile
    _parse_reaction(model, line)
  File "/Users/lopezlab/git/pysb/pysb/bng.py", line 450, in _parse_reaction
    r'#(_reverse_)?(\w+)(?: unit_conversion=(.*))?\s*$', rule).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by lh64** [comment]
Should also create a small example reproducing this error and add it to the unit tests suite.

**Comment by lh64** [comment]
Fixed
